### PR TITLE
Merge 0.5.0 branch to main

### PR DESCRIPTION
**Pull request by mirceaalexandru**

### CODE REVIEW

**Comment by mihaidma** [comment]
@AdrieanKhisbe: PR under review now.

**Comment by AdrieanKhisbe** [comment]
@mihaidma cool ! :)
(Havve a look to https://github.com/senecajs/seneca-auth/pull/53, PR for `0.5.0` with coverage)

**Comment by mihaidma** [comment]
There are 4 test out of 65 failing. Tested on Node 5.1.1, 4.1.0, 10.38, 12.9

**Comment by AdrieanKhisbe** [comment]
:tada: ! :)

@mirceaalexandru , do you want me to adapt #53 for coverage and standard seneca plugin header? :)

**Comment by mirceaalexandru** [comment]
@AdrieanKhisbe  Yes please

**Comment by AdrieanKhisbe** [comment]
Just missing the publication on npm :)

**Comment by mihaidma** [comment]
No there are still dependencies on seneca-web and seneca-user that we have to solve. Hold on for 1-2 more days until we stabilize everything.

**Comment by AdrieanKhisbe** [comment]
okey dokey :)

**Pull request merged**
