### PR TITLE
Update travis build

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**

### CODE REVIEW

**Comment by mihaidma** [comment]
@AdrieanKhisbe please update your PR so that I can review it

**Comment by AdrieanKhisbe** [comment]
incoming!

**Comment by AdrieanKhisbe** [comment]
done :)

**Comment by mihaidma** [comment]
Awesome, thank you!
I'll merge this then reuse and PR this fork: https://github.com/mihaidma/seneca-auth

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Pull request merged**
